const PDFDocument = require("pdfkit");

/**
 * ============================================================
 * Export Dashboard PDF
 * ============================================================
 *
 * Purpose
 * -------
 * Generate Workforce Analytics PDF Report.
 *
 */

const exportDashboardPDF = (dashboard, res) => {

    // Response Headers
    res.setHeader(
        "Content-Type",
        "application/pdf"
    );

    res.setHeader(
        "Content-Disposition",
        "attachment; filename=workforce-analytics-report.pdf"
    );

    // Create PDF
    const doc = new PDFDocument({

        margin: 50,

        size: "A4"

    });

    // Pipe PDF to Response
    doc.pipe(res);

    /**
     * ========================================================
     * Title
     * ========================================================
     */

    doc
        .fontSize(22)
        .text(
            "Workforce Analytics Report",
            {
                align: "center"
            }
        );

    doc.moveDown();

    doc
        .fontSize(10)
        .text(
            `Generated On : ${new Date().toLocaleString()}`
        );

    doc.moveDown();

    /**
     * ========================================================
     * Dashboard Summary
     * ========================================================
     */

    doc
        .fontSize(18)
        .text("Dashboard Summary");

    doc.moveDown(0.5);

    doc
        .fontSize(12)
        .text(
            `Recoverable Hours : ${dashboard.recoverableHours}`
        );

    doc.text(
        `Recoverable Money : ₹${dashboard.recoverableMoney}`
    );

    doc.text(
        `Departments : ${dashboard.departmentBreakdown.length}`
    );

    doc.text(
        `Applications : ${dashboard.appBreakdown.length}`
    );

    doc.text(
        `Task Categories : ${dashboard.taskBreakdown.length}`
    );

    doc.moveDown();

    /**
     * ========================================================
     * Department Breakdown
     * ========================================================
     */

    doc
        .fontSize(18)
        .text("Department Breakdown");

    doc.moveDown(0.5);

    dashboard.departmentBreakdown.forEach(

        (department) => {

            doc.text(

                `${department.department} : ${department.hours} hrs`

            );

        }

    );

    doc.moveDown();

    /**
     * ========================================================
     * Top Automation Opportunities
     * ========================================================
     */

    doc
        .fontSize(18)
        .text("Top Automation Opportunities");

    doc.moveDown(0.5);

    dashboard.automationRanking

        .slice(0, 5)

        .forEach(

            (task, index) => {

                doc.text(

                    `${index + 1}. ${task.task}`

                );

                doc.text(

                    `Recoverable Hours : ${task.repetitiveHours.toFixed(2)}`

                );

                doc.text(

                    `Recoverable Money : ₹${task.recoverableMoney.toFixed(2)}`

                );

                doc.moveDown();

            }

        );

    /**
     * ========================================================
     * Weekly Trend
     * ========================================================
     */

    doc

        .fontSize(18)

        .text("Weekly Trend");

    doc.moveDown(0.5);

    dashboard.weeklyTrend.forEach(

        (week) => {

            doc.text(

                `${week.week} : ${week.hours} hrs`

            );

        }

    );

    doc.moveDown();

    /**
     * ========================================================
     * Anomalies
     * ========================================================
     */

    doc

        .fontSize(18)

        .text("Detected Anomalies");

    doc.moveDown(0.5);

    if (dashboard.anomalies.length === 0) {

        doc.text("No anomalies detected.");

    }

    else {

        dashboard.anomalies.forEach(

            (item) => {

                doc.text(

                    `${item.type} | Employee : ${item.employeeId}`

                );

            }

        );

    }

    doc.moveDown();

    /**
     * ========================================================
     * Footer
     * ========================================================
     */

    doc

        .fontSize(10)

        .text(

            "Generated by Workforce Analytics Dashboard",

            {

                align: "center"

            }

        );

    // Finish PDF
    doc.end();

};

module.exports = {

    exportDashboardPDF

};